#!/usr/bin/env bash

# Set environment variables for dev or CI
export APP_PORT=${APP_PORT:-8888}
export DB_PORT=${DB_PORT:-33061}

if [ $# -gt 0 ];then
	docker-compose "$@"
else
	docker-compose ps
fi
